### PR TITLE
Tutorial for new members

### PR DESCRIPTION
**Pull request by Phyker**
## A lot tutorial for new members.

### CODE REVIEW

**Comment by GhostShot3** [comment]
Use "Ready to merge" label when finnish or merge you when finished.

**Comment by Phyker** [comment]
PhytonProgaming/Tutorial #1

**Comment by Phyker** [comment]
Ok, thank you for comment.

**Comment by GhostShot3** [comment]
No conflits :)

**Comment by Phyker** [comment]
Tutorial 1 will begin to be written.

**Comment by Phyker** [comment]
This will take to complete. In the end, this will be good for new members in language "Python"!

**Comment by GhostShot3** [comment]
This pullrequest have conflits,can't merge

**Comment by GhostShot3** [comment]
I wi

**Comment by GhostShot3** [comment]
Needs to remake pr.

**Pull request closed without merging**
